baseURL = "/"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "Konstantin Shibkov blog"
theme = "hello-friend"
useRelativeCover = true
summaryLength = 20
paginate = 5
TableOfContents = true
enableRobotsTXT = true
disqusShortname = 'sendel'

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
defaultTheme = "dark"
showReadingTime = false
toc = true
author = 'Shibkov Konstantin'
description = "Статьи о java и linux, руководства и мануалы"

[taxonomies]
tag = "tags"

[languages]
  [languages.ru]
    title = "Konstantin Shibkov - блог"
    subtitle = "Статьи о java и linux, руководства и мануалы"
    keywords = "java, js, php, linux, manjaro, shibkov, spring"
    copyright = ""
    menuMore = "Показать еще"
    writtenBy = "Автор"
    readMore = "Читать"
    readOtherPosts = "Другие записи"
    newerPosts = "В будущее"
    olderPosts = "В прошлое"
    minuteReadingTime = "мин на прочтение"
    dateFormatSingle = "02.01.2006"
    dateFormatList = "02.01.2006"
    toc="dfsdf"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.ru.params.logo]
      logoText = "sendel.ru"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.ru.menu]
      [[languages.ru.menu.main]]
        identifier = "about"
        name = "‍Обо мне"
        url = "/about"
